### ISSUE TITLE
[MissingPortal] MDE for GCC-H

### ISSUE THREAD

**Issue by jimtr123** [adamfowlerit/msportals.io#101]
## Portal Name ##

Microsoft Defender for Endpoint portal for US Government customers GCC-H

## Portal URL ##

What is the main URL/Site we are missing

https://securitycenter.microsoft.us

## Secondary Portal URLs ##

We try to add aka.ms links wherever we can. Do you know of a related aka.ms link for your suggestion?
Example: <https://aka.ms/teamsadmincenter>

## What portal page and section would this fit best on? ##

We are currently making our web-pages from JSON files, which page and section does this fit best with?

Government Portals

## Special Notes ##

On some of the portals, we have been adding notes. For example

Example: Using the notes to make old product name searchable for Defender products.
![Defender for Endpoint is shown with "previously Defender ATP"](https://i.imgur.com/t8by69w.png)

Example: The new versus old Exchange Portals shown below.  
![Website has two Exchange Admin Centers with the New and Old portals noted](https://i.imgur.com/mjX0gS7.png)

## Additional context ##

Suggestions or context for the portals that we should have?

This is documented here,
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/gov

**Comment by adamfowlerit** [comment]
Thanks for submitting, this has now been added.
