### ISSUE TITLE
[MissingPortal] Azure AD - My Groups - Option 2

### ISSUE THREAD

**Issue by xlZeroAccesslx** [adamfowlerit/msportals.io#103]
## Portal Name ##

My Groups (Option 2)
## Portal URL ##

https://mygroups.microsoft.com
## What portal page and section would this fit best on? ##

End User Links

**Comment by adamfowlerit** [comment]
This one was weird, as it redirects to the existing entry, but I'll add it in case Microsoft update/change something.
