### ISSUE TITLE
[MissingPortal] Azure AD Privileged Identity Management

### ISSUE THREAD

**Issue by xlZeroAccesslx** [adamfowlerit/msportals.io#104]
## Portal Name ##

Azure AD Privileged Identity Management
## Portal URL ##

https://portal.azure.com/#blade/Microsoft_Azure_PIMCommon/CommonMenuBlade/quickStart
## Secondary Portal URLs ##

aka.ms/myroles
## What portal page and section would this fit best on? ##

Admin Links

**Comment by adamfowlerit** [comment]
Added in the Azure Sub Portal section, thanks!
