### ISSUE TITLE
[MissingPortal] Microsoft 365 Adoption Hub

### ISSUE THREAD

**Issue by xlZeroAccesslx** [adamfowlerit/msportals.io#106]
## Portal Name ##

Microsoft 365 Adoption Hub
## Portal URL ##

https://adoption.microsoft.com/
## Secondary Portal URLs ##

https://aka.ms/adoptionhub
## What portal page and section would this fit best on? ##

Admin Links
## Additional context ##

Landing page for Microsoft branded M365 Adoption Resources for Adoption/Change Management Specialist and IT Administrators.

**Comment by adamfowlerit** [comment]
We either have that already or someone just added, either way it's there now!
