### ISSUE TITLE
[MissingPortal] <Missing Portal Description>

### ISSUE THREAD

**Issue by Computer-Tsu** [adamfowlerit/msportals.io#112]
## Portal Name ##
  
Microsoft Reseller Registration Portal 

## Portal URL ##
  
<https://reselleruat.microsoftcrmportals.com/>

## What portal page and section would this fit best on? ##

[Home page / Admin Links](https://msportals.io/)

**Comment by adamfowlerit** [comment]
Thank you for letting us know, added!
