### ISSUE TITLE
[MissingPortal] Microsoft Endpoint Manager Government admin center

### ISSUE THREAD

**Issue by chrisshilt** [adamfowlerit/msportals.io#120]
## Portal Name ##
Microsoft Endpoint Manager Government admin center

## Portal URL ##
https://endpoint.microsoft.us/#home

## What portal page and section would this fit best on? ##
 [US Government JSON](/_data/portals/us-govt.json)

**Comment by adamfowlerit** [comment]
Added, thanks!
