### ISSUE TITLE
[FeatureRequest] Delegated domain method for delegated access

### ISSUE THREAD

**Issue by TimonTrukker** [adamfowlerit/msportals.io#122]
Some portals accept a tenant domain for delegated access (example: https://portal.azure.com/tenantname.onmicrosoft.com works). It would be useful if this is marked within the list with an icon and hovering over the icon shows the correct syntax for that portal.

**Comment by PsychoData** [comment]
This is kind of a form of a Direct Sign in Link or Domain Hint - 
https://myapps.microsoft.com/contoso.one
https://myapps.microsoft.com/?whr=contoso.one
https://outlook.office365.com/contoso.one
https://outlook.office365.com/owa/bob.jones@contoso.one
https://outlook.office.com/owa/?realm=contoso.one&path=/calendar/view/Month
https://passwordreset.microsoftonline.com/?whr=contoso.one
https://myapps.microsoft.com/contoso.one/signin/Twitter/


you can also have **Login hints** that will usually get filled in as the username, like this one will prompt you to login as "Tinafey@contoso.one"
https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=bd53bb89-0cc1-4eb3-90b7-ba008b1f2a2c&scope=user.read&response_type=code&state=23424&login_hint=TinaFey@contoso.one

Or the best "Find your Org's SharePoint" Link we could find takes advantage of a similar function to redirect the user https://login.microsoftonline.com/login.srf?wa=wsignin1.0&wreply=https://www.office.com/launch/sharepoint%3F&LoginOptions=1 to redirect the user to https://www.office.com/launch/sharepoint/ after they login (All of the SharePoint domains vary per tenant) 


If you have other Examples of the URLs with the Domain 

You can read about some examples here 
https://docs.microsoft.com/bs-cyrl-ba/azure/active-directory/manage-apps/end-user-experiences#direct-sign-on-links
https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-authentication-for-federated-users-portal#domain-hints

**Comment by PsychoData** [comment]
It might be useful - but most of the URLs can have `/yourDomain.com/`  added 

Now ... one interesting possibility... include some field to enter their Domain information and fill it in for them...... 

so they enter would enter "Contoso.one" and it changes the link shown to them from `https://myapps.microsoft.com` to `https://myapps.microsoft.com/contoso.one/`  

That might be good option to give a way to provide the direct sign-in links without having to make another icon. 
The page is starting to get somewhat cluttered, so the more icons we are adding for each entry - the heavier it is to navigate without a significant UX redesign

**Comment by adamfowlerit** [comment]
I think your idea of having a field you can enter your domain in, and having it added to relevant links makes sense, it wouldn't add clutter that way. Is this something you or @mdjx can do?

**Comment by mvkaurelium** [comment]
Maybe just a text field like the quick filter which, if filled in, alters the links?
Something like "Create direct links for a specific user/domain" with a small validation check to confirm for a valid username or domain.
That would not make for much clutter...

**Comment by mdjx** [comment]
I haven't gone back to look at the code to see how this could be implemented, but I think at the very least we would need to modify the JSON to include a flag that the portal accepts a domain suffix. Without this, all URLs would be modified, which would result in a bunch of them becoming invalid.

**Comment by mvkaurelium** [comment]
Not only if the portal accepts a domain suffix, but also the syntax. For most portals it is enough to add the domain at the end, but not for all.

**Comment by TonnyWildeman** [comment]
When managing some things for a customer as a partner, there are partner portal enabled links. The following examples all come directly from the partner portal (e.g. https://partner.microsoft.com/commerce/customers/{customer-tenant-id}/servicemanagementpage:

Where
- {customer-tenant-id}
  2b928126-6bc6-4638-bb74-dbf0b22b9568 (just a random example GUID)
- {customer-tenant-name}
  constoso
- {customer-tenant-domain}
  contoso.com
- {partner-tenant-domain} the domain part of the upn with which the partner logs in
  fabrikam.com

- Azure Active Directory
   https://aad.portal.azure.com/{customer-tenant-domain}
- Power Platform
   https://admin.powerplatform.microsoft.com/account/login/{customer-tenant-id}
- Dynamics 365 Business Central
   https://businesscentral.dynamics.com/{customer-tenant-id}/admin
- Exchange 
   https://admin.exchange.microsoft.com/?rfr=Admin_o365&exsvurl=1&delegatedOrg={customer-tenant-domain}&mkt=en-US&Realm={partner-tenant-domain}
- Microsoft 365
   https://portal.office.com/Partner/BeginClientSession.aspx?CTID={customer-tenant-id}&CSDEST=o365admincenter
- Microsoft 365 Planner
   https://portal.office.com/Partner/BeginClientSession.aspx?CTID={customer-tenant-id}&CSDEST=o365admincenter
- Endpoint Manager
   https://endpoint.microsoft.com/{customer-tenant-domain}
- SharePoint
   https://{customer-tenant-name}-admin.sharepoint.com/
- Sway
   https://portal.office.com/Partner/BeginClientSession.aspx?CTID={customer-tenant-id}&CSDEST=o365admincenter
- Teams
   https://admin.teams.microsoft.com/?delegatedOrg={customer-tenant-domain}
- Microsoft Azure Management Portal
   https://portal.azure.com/{customer-tenant-domain}
- Azure IoT Central
   https://apps.azureiotcentral.com/myapps?tenant={customer-tenant-domain}
- Visual Studio Marketplace
   https://app.vsaex.visualstudio.com/integrationredirect/cspPartnerSignin?tenantId={customer-tenant-id}&replyto=https://marketplace.visualstudio.com
- Manage Visual Studio subscriptions
   https://app.vsaex.visualstudio.com/integrationredirect/cspPartnerSignin?tenantId={customer-tenant-id}&replyto=https://manage.visualstudio.com/Subscribers?act_id=2

It would be nice if these could be filled in and added to the portal list.

**Comment by PsychoData** [comment]
right @TonnyWildeman that's sort of related to what this was about. 
Partner Delegated Admin rights are slightly different than Azure based Delegated Admin Rights, but I believe that the example links I provided above https://github.com/adamfowlerit/msportals.io/issues/122#issuecomment-823661332 would work for you, right?

**Comment by TonnyWildeman** [comment]
@PsychoData Actually and unfortunately they don't. The one I actually need is for https://security.microsoft.com . I tried all sorts of combinations, but none worked. I also don't know where to ask for the correct partner form. I solved by creating a temp global admin and logged in with that. Sort of PIM-ish. But that's obviously not the way to go.

Core problem that is being solved in this thread is having smart links to the delegated admin portals. The list of portals is helping me already, but smart links would be awesome.

**Comment by PsychoData** [comment]
I've done security.microsoft.com through .... I guess Role Based access? Identity Governance? I get mixed up what which of those *hand waving* features are called properly. Grant the Admin Role through an Access Package / B2B Accounts

- In Customer Tenant
    - in Identity Governance, Create a [Connected Organization](https://portal.azure.com/#blade/Microsoft_AAD_ERM/DashboardBlade/elmOrganizations) for B2B  from customer to the Partner Tenant
    - Create Group to hold B2B members to assign roles and get permissions - perhaps "Partner-Sec-Analysts" - 
    - Create Security Analyst Role at M365 Defender > Settings > [Endpoints > Permissions > Roles](https://security.microsoft.com/preferences2/user_roles) 
       - This is what will decide their access level and permissions, including Live Response, R/W Access to Defender, etc
       - Assign that Defender Role to the Group you created to the B2B analysts group "Partner-Sec-Analysts"
    - Add any AzureAD Roles you want to grant at security.microsoft.com > Permissions & Roles > [Azure AD Roles](https://security.microsoft.com/aadpermissions)
    - Add any Email Security roles you want them to have access to at Permissions & Roles > [Email & Collab Permissions](https://security.microsoft.com/emailandcollabpermissions)
    - You may want to go to portal.cloudappsecurity.com > Settings Gear in Top Right > Manage Admin Access and grant your "Partner-Sec-Analysts" another "Security Reader" role or similar as well - for any incidental permissions to read Azure resource or Cloud App Security errors or similar, as a limited fall back if a permission isn't working correctly 
    - Create a Catalog and Access Package [Access Package in Identity Governance](https://portal.azure.com/#blade/Microsoft_AAD_ERM/DashboardBlade/elmEntitlement) that will grant "Group and Team" that is "Assignable to roles" 

You can tweak the Approvers/Approval policy to reference people from the customer, or your Partner Organization, or both by specifying approvers. 

And then the Employees would either go to https://myaccess.microsoft.com > Switch Directory in the top right to the customer Tenant, and request access to the role. 
OR you could send them to https://myaccess.microsoft.com/customertenant.com and it should offer it to be requested. 

They request, it goes through approval, and they can access. 

You may also be able to grant that Permission through to a Group inside the Partner Tenant, but that might need to be by GUID and I don't remember if I ever got that to work. 


OH and whenever you are setting up notifications for detections - make sure to check the "Include Organization-Specific Portal link" - and then they can click directly into that Customer's Defender Portal and not have to Switch directories THEN click, or similar

**Comment by ivandretvic** [comment]
The customization of links would complicate this site unnecessarily. Generally the real value is to use this page as a resource to find the links. I would recommend an Info icon or similar that includes how someone uses the customized link with examples as above. 
This gives a user the ability to modify their own URI where they need to use it, and we manage the info centrally for awareness.
Much easier to implement.

**Comment by PsychoData** [comment]
hmmm - if we did implement the customized-per-tenant-url capability - it would be handy to have the "info" button that could take you to the entry area. 
"You can link directly to a specific tenant like https://myapps.microsoft.com/contoso.one . [Try it with your domain](not a real link yet)!"

**Comment by TonnyWildeman** [comment]
@PsychoData thanks for the steps. I'll implement them when I need to access the tenant again.

@ivandretvic I agree that the core value of the site is the list of all the portals. Having a bookmarkable url would be a great addition to the site.

The generation of the links needn't be necessarily complex. Use a bookmarkable url e.g. https://msportals.io/contoso.onmicrosoft.com/a34ee217-3247-413f-b206-5f0d859a160a as the basis for the parameters in the portal resource links. Check if the parameters are formatted correctly and generate the portal links on the page based on these parameters. Because of the static site generation, the generating of the links can only be done client side. Development steps: add the template url to the .json schema and jsons as optional. Add the templated links to the primaryurl <a> tag in a data-template-delegated attribute. Create some simple library-less js to read in the bookmarked url. Test for existence of the parameters. Validate the parameters. Find all <a> tags with (filled in) data-template-delegated and generate the url. Replace the current href (primaryurl) with the generated template.

When I find the time and this hasn't been done yet, I'll create a PR with this.

**Comment by PsychoData** [comment]
The issue is more of one that there are several different forms that these can take.

 Some of them use tenant name, some of them use any domain from the tenant, some of them use the tenant guid. 

If you are adding in partner links as well instead of just tenant-directed links, then you also sometimes need to use the partner tenant GUID, or the partner tenant name or domain. 

It is certainly doable, though it may have to include looking up the other parts if The site doesn't know them already. Perhaps if it only currently knows me customer tenant domain and the partner guid, and needs the customer GUID. et cetera

**Comment by adamfowlerit** [comment]
We've got the B2B link now - so if there's other URLs that need something else to support delegated access @TonnyWildeman @PsychoData @ivandretvic @mdjx please respond :)

**Comment by TonnyWildeman** [comment]
Thanks for adding. I haven't encountered a url that I needed that wasn't supported here in a loooong time.

And also thanks for creating the portal in the first place!

**Comment by adamfowlerit** [comment]
No worries, and if you DO come across one please let me know!
