### ISSUE TITLE
[MissingPortal] Report unsafe website

### ISSUE THREAD

**Issue by Computer-Tsu** [adamfowlerit/msportals.io#139]
## Portal Name ##
Report unsafe website 

## Portal URL ##
<https://feedback.smartscreen.microsoft.com/feedback.aspx>

## What portal page and section would this fit best on? ##
[End User Links/Apps](https://msportals.io/userportals)   | [End User JSON](/_data/portals/user.json)

## Special Notes ##
Keywords: unsafe, report, malicious, spam, malware, security
Also available in Chromium Edge, Menu, Help and Support, Report unsafe site

**Comment by adamfowlerit** [comment]
https://feedback.smartscreen.microsoft.com/feedback.aspx just gives me a 'Bad Request' and the top level domain https://feedback.smartscreen.microsoft.com is a generic 'Your App Service app has been created' - what's the starting link for this portal?

**Comment by Computer-Tsu** [comment]
The URL provided is a POST result, not a GET, so investigating if another URL works for manual form entry.

**Comment by Computer-Tsu** [comment]
Internet Explorer on Windows 10 also goes to https://feedback.smartscreen.microsoft.com/feedback.aspx
(Tools, Safety, Report unsafe website). Same behavior where the current website URL is provided and can't be changed on the subsequent form.

**Comment by adamfowlerit** [comment]
Is this the result you're expecting to see?

https://feedback.smartscreen.microsoft.com/feedback.aspx?url=

**Comment by Computer-Tsu** [comment]
https://feedback.smartscreen.microsoft.com/feedback.aspx?t=0&url=_<URL to be reported>_

For a traditional form, two other sites appear available. One requests a login, the other does not.

https://www.microsoft.com/en-us/wdsi/support/report-unsafe-site
Help us handle your submission efficiently by signing in with your personal Microsoft account or your corporate account. Corporate account holders can report multiple URLs in a single submission.

https://www.microsoft.com/en-us/wdsi/support/report-unsafe-site-guest
Same as above if you click the Continue as Guest instead of logging in.

**Comment by Computer-Tsu** [comment]
Related is Submit a file for malware analysis
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by adamfowlerit** [comment]
All 3 links on the main page now, thanks!
