### ISSUE TITLE
[MissingPortal] Windows 365

### ISSUE THREAD

**Issue by kDylanHayes** [adamfowlerit/msportals.io#140]
## Portal Name ##

Please add the Windows 365 portal as Windows 365 is coming out on August 2 
Source: https://www.microsoft.com/en-us/windows-365
Archive: https://archive.is/6a2fD
## Portal URL ##

windows365.microsoft.com

![image](https://user-images.githubusercontent.com/57426223/125720969-3b7f3896-e903-4712-9296-2b87a60b78a0.png)
Source: https://www.youtube.com/watch?v=qKG8r1NERl4

## Secondary Portal URLs ##

Unknown
## What portal page and section would this fit best on? ##

Best fits under End User Links as the Cloud PC will be managed in the Endpoint Manager (Intune) Portal
As shown in this Microsoft Mechanics video
https://www.youtube.com/watch?v=V14Ia2uwrtk

**Comment by adamfowlerit** [comment]
Added to user page under End User Portals - General
