### ISSUE TITLE
[BUG] Update Microsoft 365 Lighthouse to Public Preview

### ISSUE THREAD

**Issue by kDylanHayes** [adamfowlerit/msportals.io#141]
## Describe the bug ##

Microsoft 365 Lighthouse is now in Public Preview please update _italics_ text 

> Today, we are excited to announce Microsoft 365 Lighthouse Preview. Microsoft 365 Lighthouse is currently available as a public preview and provides managed service providers with one central location and standard security configuration templates to secure devices, data, and users for small and medium business customers using Microsoft Business Premium.

Source: https://www.microsoft.com/security/blog/2021/07/14/how-microsoft-security-empowers-partners-to-build-customer-trust/
Archive: https://archive.is/BrsFc

![image](https://user-images.githubusercontent.com/57426223/125718242-e7527ad5-a00b-45fa-a8dc-44e936e3267a.png)

**Comment by adamfowlerit** [comment]
All good, closing :)
