### ISSUE TITLE
[FeatureRequest] Add an icon flag(s) if the portal is B2B compatible and example URL

### ISSUE THREAD

**Issue by JustinGrote** [adamfowlerit/msportals.io#145]
Many portals are B2B compatible, meaning that B2B guest users can use the portals if they have appropriate rights. Teams, Exchange, Endpoint, Security, etc. so there should be a flag calling out which will work and which dont. Some may have partial support so an asterisk with details below would also be great.

This would be helpful for MSPs and such who prefer to unify logins from their managing tenant where possible rather than establishing a bunch of accounts in every tenant.

**Comment by adamfowlerit** [comment]
Solved thanks to @jlaundry a while back!

**Comment by JustinGrote** [comment]
@adamfowlerit awesome thanks!
