### ISSUE TITLE
[https://myaccount.microsoft.com/] <My Account>

### ISSUE THREAD

**Issue by AntonUdalow** [adamfowlerit/msportals.io#146]
## Portal Name ##

My Account
## Portal URL ##

https://myaccount.microsoft.com/
## What portal page and section would this fit best on? ##

| [End User Links/Apps](https://msportals.io/userportals)   | [End User JSON](/_data/portals/user.json)             |

**Comment by PsychoData** [comment]
This is already there 
https://msportals.io/userportals?search=myaccount
![image](https://user-images.githubusercontent.com/3719116/127419633-ae9f3a65-b1cb-4b1f-8c7b-21b6823206d8.png)
