### ISSUE TITLE
[MissingPortal] Windows Release Health

### ISSUE THREAD

**Issue by Computer-Tsu** [adamfowlerit/msportals.io#147]
## Portal Name ##
Windows Release Health

## Portal URL ##
<https://docs.microsoft.com/en-us/windows/release-health/>

## Special Notes ##
Official information on Windows 10 releases and servicing milestones, plus resources, tools, and news about known issues and safeguards to help you plan your next update

--Reference: Windows 10 release information and servicing options
--What's New
--Get Started: IT tools for Windows 10
--Architecture
--Learn: How to plan for, prepare & deploy updates for Windows 10
--Reference: Frequently asked questions- Windows lifecycle

## Additional context ##
part of Microsoft Documentation library

**Comment by adamfowlerit** [comment]
There's a bunch of portals like these - do they have any function beyond documentation?

Wondering if we do these, and if so they'd need their own section

**Comment by adamfowlerit** [comment]
After thinking about it, I won't let the URL dictate it's value - it's a portal of info on the docs page with high value info and links. This has been added under the health / status section.
