### ISSUE TITLE
[FeatureRequest] Add Visio as a link

### ISSUE THREAD

**Issue by KiraUsagi** [adamfowlerit/msportals.io#151]
## Describe the solution you'd like ##

Could the following link be added to the end users section for Visio on the web?
https://www.office.com/launch/visio

## Additional context ##

Visio online is now included with most M365 licenses 🎉
https://www.microsoft.com/en-us/microsoft-365/blog/2021/06/09/bringing-visio-to-microsoft-365-diagramming-for-everyone/

**Comment by adamfowlerit** [comment]
Great point - now added to the user section!
