### ISSUE TITLE
[BUG] securescore.microsoft.com doesn't seem to work anymore

### ISSUE THREAD

**Issue by Oppedijk** [adamfowlerit/msportals.io#157]
## Describe the bug ##

securescore.microsoft.com doesn't seem to work anymore

## To Reproduce ##

1. Go to 'securescore.microsoft.com'
2. See error

## Expected behavior ##

Expect to see the secure score pages

## Desktop (please complete the following information) ##

- OS: Windows 11
- Browser: Edge
- Version (latest)

**Comment by adamfowlerit** [comment]
Appears this has moved to https://security.microsoft.com/securescore and I'm updating the link now. Thanks!
