### ISSUE TITLE
[MissingPortal] ISV Studio

### ISSUE THREAD

**Issue by YannickRe** [adamfowlerit/msportals.io#162]
## Portal Name ##
ISV Studio

## Portal URL ##
https://isvstudio.powerapps.com/home

## Secondary Portal URLs ##
https://aka.ms/ISVStudio/

## What portal page and section would this fit best on? ##
Not sure. It's an ISV Portal, not end-user or admin so I didn't know which section to pick...

**Comment by adamfowlerit** [comment]
End users is designed for a standard worker, so I think this fits better in Admin.

**Comment by adamfowlerit** [comment]
Added! Thank you
