### ISSUE TITLE
[MissingPortal] Microsoft URLs and IP address ranges

### ISSUE THREAD

**Issue by Computer-Tsu** [adamfowlerit/msportals.io#164]
## Portal Name ##
Office 365 URLs and IP address ranges

## Portal URL ##
https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges

## Secondary Portal URLs ##
https://aka.ms/o365ip

## Special Notes ##
The Microsoft Docs page is the same destination as the aka.ms URL
There are other IP and domain name lists not included here, such as for Azure, or Windows Updates
Others linked to from here include: Office 365 Worldwide (+GCC) | Office 365 operated by 21 Vianet | Office 365 U.S. Government DoD | Office 365 U.S. Government GCC High

## Additional context ##
These are lists of Microsoft IP addresses and domain names which should be added to an organization's firewall rules or antivirus allowed lists, usually as always allowed so that Office 365, Azure, Windows Updates, and other services are not disrupted by false-positive security blocks.

**Comment by adamfowlerit** [comment]
Thinking about the feasibility of having a separate site for this - rather than portals, it'd be all the other stuff that doesn't fit in - links to downloads, key doco info etc. Open to thoughts on this.

**Comment by adamfowlerit** [comment]
Alright I added it to the other section on the main page :)
