### ISSUE TITLE
[MissingPortal] Azure Data Explorer

### ISSUE THREAD

**Issue by pminnebach** [adamfowlerit/msportals.io#169]
## Portal Name ##

Azure Data Explorer

## Portal URL ##

https://dataexplorer.azure.com/
and / or
https://dataexplorer.azure.com/freecluster

## Secondary Portal URLs ##

https://aka.ms/kustofree (this is only for the second of the above links)

## What portal page and section would this fit best on? ##
Home Page --> Developer Portals

## Additional context ##

https://techcommunity.microsoft.com/t5/azure-data-explorer-blog/start-for-free-azure-data-explorer-kusto-cluster/ba-p/3253401

https://docs.microsoft.com/en-us/azure/data-explorer/start-for-free-web-ui

Not sure if you'd want to link to only the actual portal, or also the page where you can create a free cluster, or both.

**Comment by adamfowlerit** [comment]
Thanks for submitting, I've added https://dataexplorer.azure.com/ to the Developer Portals section and added the aka.ms link.
