### ISSUE TITLE
[MissingPortal] Form Recognizer Portal

### ISSUE THREAD

**Issue by vrodrigues-msft** [adamfowlerit/msportals.io#179]

**Comment by adamfowlerit** [comment]
What's the URL for this one?

**Comment by vrodrigues-msft** [comment]
Hey Adam,

I totally thought that I add to the comments: https://formrecognizer.appliedai.azure.com/

Regards,

Victor Hugo Y. Rodrigues
"Loyalty, Discipline, Respect and Generosity"
Enterprise Digital Specialist | Data & AI | Microsoft - EMEA
Mobile: +353 87 349 9681
***@***.******@***.***>
***@***.***
***@***.*** ***@***.***   ***@***.*** ***@***.***

**Comment by adamfowlerit** [comment]
All good - added under the developer section, but let me know if you think it fits somewhere better.
