### ISSUE TITLE
[MissingPortal] Health dashboard

### ISSUE THREAD

**Issue by GruberMarkus** [adamfowlerit/msportals.io#198]
## Portal Name ##
Health dashboard

## Portal URL ##
https://admin.microsoft.com/AdminPortal/Home?#/healthoverview

## What portal page and section would this fit best on? ##
/_data/portals/admin.json

## Special Notes ##
View data about your ‎Microsoft 365‎ apps and services, and see recommended actions to keep your organization up-to-date and secure. This page is in preview.

**Comment by adamfowlerit** [comment]
Sub portal that although important I'm not sure merits a dedicated link

**Comment by GruberMarkus** [comment]
I agree with you. What do you think about adding the description of the sub portal to the main portal?

**Comment by adamfowlerit** [comment]
This link doesn't work anymore (goes to home page) but we do have https://admin.microsoft.com/AdminPortal/Home#/servicehealth under the Health section.
