### ISSUE TITLE
[MissingPortal] Message center

### ISSUE THREAD

**Issue by GruberMarkus** [adamfowlerit/msportals.io#199]
## Portal Name ##
Message center

## Portal URL ##
https://admin.microsoft.com/AdminPortal/Home?#/MessageCenter

## What portal page and section would this fit best on? ##
/_data/portals/admin.json

**Comment by adamfowlerit** [comment]
I'll add this as Message Center is critical and people would potentially go to look it up by name.

**Comment by adamfowlerit** [comment]
Closing as it's a subportal :(
