### ISSUE TITLE
[FeatureRequest] Clear button on search text field

### ISSUE THREAD

**Issue by ivandretvic** [adamfowlerit/msportals.io#204]
## Is your feature request related to a problem? Please describe ##

As the links all load in a new window, im often having to clear the text with backspace and often i find it less efficient than if i could use the mouse.

## Describe the solution you'd like ##

A 'x' or the word 'clear' at the end of the search box. When mouse clicks on it, it should clear the contents of the text field, and put cursor focus in the text field.

## Describe alternatives you've considered ##

Clicking the logo reloads the page, however this takes a fraction longer. Not ideal.

**Comment by adamfowlerit** [comment]
UI and UX options like this would be great - just need someone with the ability to code them.
