### ISSUE TITLE
[BUG] Site certs messed up and opens in http vs https

### ISSUE THREAD

**Issue by ayenampudi** [adamfowlerit/msportals.io#208]
## Describe the bug ##

Site is opening in http vs https

## To Reproduce ##

Just launch the site

## Expected behavior ##

SSL 

## Screenshots ##
![image](https://user-images.githubusercontent.com/43830637/187787863-ddb29052-7a0e-48f9-9000-4fa24c7b9d03.png)

**Comment by davidbmarker** [comment]
@ayenampudi,
I tested using the following browser and received no errors; I verified on each device that I am using the most current certificate, dated from ‎Friday, ‎August ‎5, ‎2022, 11:31:40 PM to ‎Thursday, ‎November ‎3, ‎2022, 11:31:39 PM.

- Windows 11 - 22H2 - 25188.1000
  - Google Chrome 105.0.5195.54 (Official Build) (64-bit)
  - Microsoft Edge 104.0.1293.70 (Official Build) (64-bit)
  - Microsoft Edge 106.0.1367.0 (Official Build) canary (64-bit)
 
- Windows 10 - 21H2 - 19055.1889
  - Microsoft Edge 104.0.1293.70 (Official Build) (64-bit)
 
- iOS 15.6.1
  - Safari 15.6
  - Microsoft Edge 106
  
- Android 11
  - Google Chrome 105
  - Microsoft Edge 104
  - Microsoft Edge 106

Are you saying that when you open the site in http it doesn't redirect to https?

**Comment by adamfowlerit** [comment]
Found that for some reason, the auto redirect to https option was unticked - I've ticked it, will give it a little time to see if it kicks in.

**Comment by adamfowlerit** [comment]
Fixed for me - please confirm @ayenampudi

**Comment by ayenampudi** [comment]
Thank you for the quick fix. Seems to work fine now.

**Comment by ayenampudi** [comment]
One issue I still see is, there is no auto http to https redirect....I got to hit the https url to enter a secure session.

**Comment by ayenampudi** [comment]
hitting this url http://msportals.io/?search= still takes me to the http site vs https

**Comment by davidbmarker** [comment]
I also confirm that the server's HTTP to HTTPS redirect isn't working. When I tested between Microsoft Edge 104.0.1293.70 and Microsoft Edge 106.0.1367.0, 106.0.1367.0 did redirect. A setting within the browser was doing the redirect, but 104.0.1293.70 on a managed computer, I didn't have that setting option, but on another computer, it did have that option.

@ayenampudi, what browser and build are you using?

@adamfowlerit, are you able to confirm that your browser doesn't have that setting on and it still works with you?

![Screenshot 2022-09-01 121102](https://user-images.githubusercontent.com/44678104/187962085-95259dcf-d349-46c8-a5e6-52959c77303b.png)

For more information:
https://blogs.windows.com/msedgedev/2021/06/01/available-for-preview-automatic-https-helps-keep-your-browsing-more-secure/

**Comment by adamfowlerit** [comment]
edge://flags/#edge-automatic-https - disabling this, restarting browser, going to msportals.io still takes me to https rather than http... but http://msportals.io/?search= does not redirect. 

Just checked and this change is still pending, so let's wait a bit longer:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/18343337/188034761-0433b492-c4ad-4366-a74a-f4476a200d36.png">

**Comment by adamfowlerit** [comment]
So the main site will auto-redirect, but nothing else will. If anyone can offer assistance to fix this please do.

**Comment by JackStuart** [comment]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/42309435/233565506-f2ee24c2-00d9-444e-a731-93a84c0324d1.png">
Looks to be working now

**Comment by adamfowlerit** [comment]
This appears to be working fine now
