### ISSUE TITLE
[MissingPortal] Microsoft Azure Government

### ISSUE THREAD

**Issue by allendevans** [adamfowlerit/msportals.io#209]

**Comment by adamfowlerit** [comment]
Need a bit more info on this one sorry!

**Comment by allendevans** [comment]
@adamfowlerit ok ... like what?  if you don't list it, i can't provide it.  !snarky

did you attempt the URL?

**Comment by adamfowlerit** [comment]
I don't see the URL sorry! What is it?

**Comment by allendevans** [comment]
crap ... i put it in -- how'd i manage to screw that up?!  

portal.azure.us

**Comment by allendevans** [comment]
it's listed for another site, but this is the root ... where most folks will go to login, i suppose.

**Comment by adamfowlerit** [comment]
Added portal.azure.us to the Govt area :) Thank you!

**Comment by allendevans** [comment]
**whew!**  found it ...

![image](https://user-images.githubusercontent.com/55066026/187834522-e7366074-e5b2-4aff-bf7e-cd769b836be4.png)

i'm hapless ... but not that bad.

**Comment by allendevans** [comment]
do you know the program name where MS employees receive a stipend for Azure usage?  

thinking it might help Aleksei Polkovnikov keep Azure Charts up and running.
