### ISSUE TITLE
[MissingPortal] shortcut that released by Microsoft recently

### ISSUE THREAD

**Issue by limjianan-camelody** [adamfowlerit/msportals.io#212]
Not sure worth to add these into msportals?
https://github.com/microsoft/aka#readme

<html>
<body>

aka.ms | Command | Portal Blade
-- | -- | --
aka.ms/ad/ca | ca | Conditional Access
aka.ms/ad/pim | pim | Privileged Identity Management
aka.ms/ad/users | users | Users
aka.ms/ad/groups | groups | Groups
aka.ms/ad/devices | devices | Devices
aka.ms/ad/apps | apps | Enterprise Applications
aka.ms/ad/appreg | appreg | Application Registrations
aka.ms/ad/auth | auth | Authentication Methods Policies
aka.ms/ad/legacymfa | legacymfa | Legacy MFA
aka.ms/ad/guests | guests | Guest Access Settings
aka.ms/ad/logs | logs | Sign in Logs
aka.ms/ad/xtap | xtap | Cross Tenant Access Settings
aka.ms/ad/roles | roles | Azure AD Roles
aka.ms/ad/sspr | sspr | Password Reset
aka.ms/ad/security | security | Security
aka.ms/ad/mfaunblock | mfaunblock | MFA Unblock
aka.ms/ad/reviews | reviews | Access Reviews
aka.ms/ad/score | score | Secure Score
aka.ms/ad/license | license | Licenses
aka.ms/ad/synclog | synclog | AAD Connect Sync Errors
aka.ms/ad/adfslog | adfslog | ADFS Log
aka.ms/ad/consent | consent | Consents and Permissions
aka.ms/ad/support | support | Support
aka.ms/ad/list | list | List all these shortcuts

</body>
</html>

<html>
<body>
<h2 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Microsoft Admin Portals</h2>

aka.ms | Page
-- | --
aka.ms/azad | Azure AD Portal
aka.ms/ge | Graph Explorer
aka.ms/in | Intune

</body>
</html>

<html>
<body>
<h2 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Microsoft User Portals</h2>

aka.ms | Page
-- | --
aka.ms/sspr | Self Service Password Reset
aka.ms/mysecurity | My Security
aka.ms/myapps | My Apps
aka.ms/my-account | My Account
aka.ms/my-groups | My Groups
aka.ms/my-access | My Access Packages
aka.ms/mystaff | My Access Packages
aka.ms/mfasetup | Alternative for My Security

</body>
</html>

**Comment by MacMatt** [comment]
Maybe it's worth a dedicated Tab not to pollue end user links

**Comment by adamfowlerit** [comment]
We've got the aka.ms icon we can use for all these against the existing links to the portals, just need some time to go through and add them all - if anyone wants to feel free to do a few and submit :)

**Comment by MacMatt** [comment]
I'm affraid I have absolutely no idea of how working on Gitub or doing what could help you save time :-(

**Comment by adamfowlerit** [comment]
All good @MacMatt and thanks @JackStuart for doing it!
