### ISSUE TITLE
[MissingPortal] <App Assure>

### ISSUE THREAD

**Issue by Computer-Tsu** [adamfowlerit/msportals.io#214]
## Portal Name ##
App Assure

## Portal URL ##
Unknown URL for App Assure users

## What portal page and section would this fit best on? ##

Microsoft Licensing/Support Portals

## Special Notes ##
I haven't used App Assure personally and lack direct knowledge if there is a portal or dashboard after signing up and logging in. It's a support and compatibility focused department in Microsoft. They provide free assistance with application issues arising from OS upgrades or installing security updates.

**Comment by PsychoData** [comment]
I believe this may be provided through https://fasttrack.microsoft.com/ based off some searching around? 
I'm not sure, though and couldn't find much specific on how to access App Assure. 
Fast Track is currently listed on the main portals page, though.

I BELIEVE that App Assure is possibly an "umbrella" term for Microsoft Support working with you for no cost when an app is not working correctly. As opposed to some cases where your App might be working correctly, but you just don't know how to correctly USE the app. 

If anyone can provide better Documentation of Fast Track vs App Assure, and/or a proper place to "access" it, we might be able to add this, or possibly modify the "Fast Track" listing to mention App Assure.

**Comment by adamfowlerit** [comment]
App Assure is offered via FastTrack and the signin from here https://www.microsoft.com/en-us/fasttrack/microsoft-365/app-assure takes you to the fasttrack URL.

Agree on note, added keyword to FastTrack notes.
