### ISSUE TITLE
[Duplicate] Power Platform is listed twice for GCC High

### ISSUE THREAD

**Issue by SamErde** [adamfowlerit/msportals.io#216]
This is actually a duplicate portal entry, but I didn't see a label for that kind of issue yet.  

## Portal Name ##
Power Platform

## Portal URL ##
https://high.admin.powerplatform.microsoft.us/environments?l=en-US

## What portal page and section would this fit best on? ##
US Govt, GCC High

| Website Page                                              | JSON Source                                            |
|---------------------------------------------------------- |------------------------------------------------------- |
| [US Government Links](https://msportals.io/usgovt)        | [US Government JSON](/_data/portals/us-govt.json)     |

**Comment by SamErde** [comment]
Fixed with PR #217 that removes the extra entry.

**Comment by SamErde** [comment]
Sorry! _NOW_ is see the duplicate tag! Can I change the tag after submitting an issue?

**Comment by SamErde** [comment]
Tried to open a new issue as duplicate, but that's not an available issue/label, so I'm back with this one. 🤣

**Comment by davidbmarker** [comment]
@SamErde, I think I fixed it for you. Waiting for @adamfowlerit to look it over and push the commit. Thanks for your help and contribution to the community!

**Comment by SamErde** [comment]
Cheers!

**Comment by adamfowlerit** [comment]
Thank you @davidbmarker and @SamErde for sorting it out, commit pushed :)
