### ISSUE TITLE
[FeatureRequest] Incorporate Microsoft acronyms glossary

### ISSUE THREAD

**Issue by tplas** [adamfowlerit/msportals.io#239]
## Is your feature request related to a problem? Please describe ##

Some folks have put together a really decent glossary of Microsoft acronyms, that might help people trying to navigate proper selections in the portals list.

## Describe the solution you'd like ##

Maybe provide a link somewhere on the main page to:
   https://tpm.ms/TLA

The content is unfortunately a bit "branded"; perhaps you can work out something with the author, to provide a version that's less branded (but still attributed to them)?

**Comment by adamfowlerit** [comment]
Good idea, I've added this to the third party links!
