### ISSUE TITLE
[BUG] Microsoft365DSC classification and aka.ms URL

### ISSUE THREAD

**Issue by Computer-Tsu** [adamfowlerit/msportals.io#245]
## Describe the bug ##

Portal may be located in wrong category.

## To Reproduce ##

1. Go to '3rd party'
2. Search for ['DSC'](https://msportals.io/3rdparty?search=dsc#non-microsoft-owned-3rd-party-portals)
3. See that site is here and not under the Microsoft category.
<br>
These portals are not Microsoft owned or controlled

Microsoft365DSC 
 https://microsoft365dsc.com/

## Expected behavior ##

This is a Microsoft owned product? Although it is a tool to download and install on your own system and is not hosted on Microsoft servers.

## Additional context ##

If applicable, [Microsoft short link **M365DSC**](https://aka.ms/M365DSC).

**Comment by adamfowlerit** [comment]
So this one is a bit of a grey area, which is why I put it into 3rd party. The site says:

"Microsoft365DSC is the most comprehensive and complete solution to have your Microsoft 365 tenant configuration simple and stable. It's an Open-Source initiative hosted on [GitHub](https://github.com/Microsoft/Microsoft365DSC), led by Microsoft engineers and maintained by the community."

Because it's maintained by the community and led by MS engineers, it feels more like a side project and not going through our normal official vetting process of anything we'd publish publicly. Happy to be convinced otherwise!

**Comment by Computer-Tsu** [comment]
To compare with a similar project, Mouse without Borders, which had a shortcut MS URL, made by a MS engineer too. MWB was promoted up through Microsoft Garage and is now a Powertoys component.

I think 365DSC will become more officially recognized. It already has a couple similar aspects.

Having it listed in 3rd party puts a description by it declaring that there isn't a connection with Microsoft which I feel is more wrong than the current tentative connection.

Some may argue that Lighthouse is the Official tool that is similar function and 365DSC won't be promoted to a more supported/officially recognized MS tool.

**Comment by PsychoData** [comment]
As it is open-source (though run by Microsoft), I don't think that Microsoft would call it "First Party" or built-in feature. 
Since you have to run it yourself, and it isn't provided BY Microsoft, I think it makes more sense to keep it as a "3rd Party" portal

**Comment by PsychoData** [comment]
That ultimately is just an open-source tool that YOU will provide to YOURSELF, through use of the PowerShell code and potentially BluePrints, etc. 

This same kind of mentality could apply to a LOAD of Microsoft and Community provided PowerShell Modules and other tools as well. In THIS case, Microsoft is Administering it and SHOULD be validating any contributions for safety, but they would certainly not claim responsibility for it.   

Safer to imply they are NOT "Official" Microsoft, than to have someone misunderstand trust it as an OFFICIAL tool.

**Comment by adamfowlerit** [comment]
aka.ms URLs definitely do not confirm it to be official Microsoft, I've seen plenty of things that link off to third party solutions. I think that's a bit of a problem in itself with aka.ms and letting so many people create links on it :)

I agree on erring on the side of caution and making it clear it's not an official tool.
