### ISSUE TITLE
[MissingPortal] Microsoft for Non-Profits

### ISSUE THREAD

**Issue by Computer-Tsu** [adamfowlerit/msportals.io#246]
## Portal Name ##
Microsoft Nonprofits

## Portal URL ##
<https://nonprofit.microsoft.com/#/signin>
<https://nonprofit.microsoft.com/en-us/getting-started>
<https://www.microsoft.com/en-us/nonprofits/offers-for-nonprofits>

## Secondary Portal URLs ##
<https://aka.ms/nonprofitgetstarted>

<https://aka.ms/nonprofitportal>

## What portal page and section would this fit best on? ##
 [Home page / Admin Links](https://msportals.io/)

## Special Notes ##
related 3rd party portal is [techsoup.org](https://www.techsoup.org/microsoft)

**Comment by adamfowlerit** [comment]
Thanks, added to main admin page under others, didn't add the 3rd party as they appear to be one of many businesses selling the discounted prices?
