### ISSUE TITLE
[BUG] Microsoft 365 Lighthouse is now in General Availability, not Public Preview

### ISSUE THREAD

**Issue by OzmeisterO** [adamfowlerit/msportals.io#248]
## Describe the bug ##

The list shows Microsoft 365 Lighthouse with "Public Preview" next to it.  Chris Boyd (the product manager of Lighthouse at Microsoft) contacted me to highlight that Lighthouse is now General Availability so the "Public Preview" tag can be removed.

## To Reproduce ##

N/A

## Expected behavior ##

See Microsoft 365 Lighthouse without the "Public Preview" tag

## Desktop (please complete the following information) ##

N/A

## Smartphone (please complete the following information) ##

N/A

## Additional context ##

Awesome work compiling this list.  I shared it on LinkedIn and people are loving it - thank you!

**Comment by adamfowlerit** [comment]
Thank you, have removed the 'Public Preview' tag!
