### ISSUE TITLE
[BUG] Training Links page isn't showing any of the items defined in the JSON

### ISSUE THREAD

**Issue by adamfowlerit** [adamfowlerit/msportals.io#256]
I'm trying to create a new page for Training - Exams/Certifications. I've managed to make the button and get the header of the training section, but can't get the training.json content to show up.

Can anyone help?

![image](https://github.com/adamfowlerit/msportals.io/assets/18343337/14cb5cab-bcb1-4214-ad79-5985fbd9d720)

**Comment by PsychoData** [comment]
Previously the Default Layout would only include QuickFilter if the title included "Portals", so it would show on "User Portals" or "Government Portals" but not on the About page, for instance. 
https://github.com/adamfowlerit/msportals.io/blob/0f1b027bcd57e1643beea1c15a2c88e2014981dc/_layouts/default.html#L52-L54

QuickFilter doesn't JUST handle the searching, but also handles "Un-hiding" (showing), all of the entries (usually Portals) for the page

Added QuickFilter to "Training Links" page, and now it works
