### ISSUE TITLE
[MissingPortal] Update My group user portal for group types

### ISSUE THREAD

**Issue by JustInnIO** [adamfowlerit/msportals.io#271]
## Portal Name ##
Two portals to manage groups as owner.
1. is for security and M365 groups
2. To be able to manage distribution groups an user page of the exchange admin center needs to be used by the user

**Name**
1. My groups
2. My groups

**Notes**
1. Security groups, Microsoft 365 groups
2. Distribution lists

## Portal URL ##
1. https://myaccount.microsoft.com/groups
2. https://admin.exchange.microsoft.com/?page=groups#/

## Secondary Portal URLs ##
N/A

## What portal page and section would this fit best on? ##

| Website Page                                              | JSON Source                                            |
|---------------------------------------------------------- |------------------------------------------------------- |
| [End User Links/Apps](https://msportals.io/userportals)   | [End User JSON](/_data/portals/user.json)             |

## Special Notes ##
1. Security groups, Microsoft 365 groups
2. Distribution lists

## Additional context ##
Old link https://account.activedirectory.windowsazure.com/r#/groups is outdated and doesnt work anymore.

**Comment by adamfowlerit** [comment]
Thanks @JustInnIO - Updated the My Groups link, and added a second one for the EAC method! :)

**Comment by JustInnIO** [comment]
Thanks for updating!
For whoever finds this: By default over https://admin.exchange.microsoft.com/?page=groups#/ any user in the tenant can create and manage their distribution groups. If you want to disable it, you need to adjust the "Default Role Assignment Policy" in Exchange to disable that users can at all manage distribution groups.
https://learn.microsoft.com/en-us/exchange/troubleshoot/groups-and-distribution-lists/prevent-users-create-manage-dg
