### ISSUE TITLE
[MissingPortal] Multi-tenant management in Microsoft Defender

### ISSUE THREAD

**Issue by christoffel1237** [adamfowlerit/msportals.io#279]
## Portal Name ##
Multi-tenant management in Microsoft Defender

## Portal URL ##
https://mto.security.microsoft.com

## What portal page and section would this fit best on? ##
https://github.com/adamfowlerit/msportals.io/blob/master/_data/portals/admin.json
Microsoft Defender / Security IT Admin Portals

**Comment by christoffel1237** [comment]
Thank you for adding the portal.

**Comment by adamfowlerit** [comment]
Thank you for submitting! :)
