### ISSUE TITLE
[MissingPortal] <Missing Portal Description>

### ISSUE THREAD

**Issue by Computer-Tsu** [adamfowlerit/msportals.io#281]
## Portal Name ##
Windows App

## Portal URL ##
[]https://windows.cloud.microsoft/

## Special Notes ##

Windows App securely connects you to Windows desktops and apps on a device of your choice from:

- Azure Virtual Desktop
- Windows 365
- Microsoft Dev Box
- ~~Remote Desktop Services~~
- ~~Remote PC~~

**Comment by Computer-Tsu** [comment]
It's a tool, not so much an admin portal.

**Comment by adamfowlerit** [comment]
I've just tested and this ends up going to https://windows365.microsoft.com/ent

I'll put this under the end user portals.
