### ISSUE TITLE
Microsoft TI portal is now retired

### ISSUE THREAD

**Issue by jkerai1** [adamfowlerit/msportals.io#284]
https://ti.defender.microsoft.com/ is retired, the experience is now embedded into https://security.microsoft.com/intel-explorer

![image](https://github.com/user-attachments/assets/46b7995b-e3fd-4f44-a30e-2fb38de2a461)

Not inherently wrong to have this URL but may as well save the redirect or tag as old

**Comment by adamfowlerit** [comment]
Thanks for that, I'll just keep the entry and put the new URL. Done!
