### ISSUE TITLE
[MissingPortal] Azure Virtual Desktop 

### ISSUE THREAD

**Issue by OrionWithrow-OHIT** [adamfowlerit/msportals.io#286]
## Portal URL ##
https://portal.azure.com/#view/Microsoft_Azure_WVD/WvdManagerMenuBlade/~/overview

**Comment by adamfowlerit** [comment]
Added, thank you @OrionWithrow-OHIT ! If you pick up any other core products like this which are technically a sub portal but worth listing, please let us know.
