### ISSUE TITLE
[MissingPortal] Azure Update Manager

### ISSUE THREAD

**Issue by OrionWithrow-OHIT** [adamfowlerit/msportals.io#287]
## Portal Name ##
Azure Update Manager

## Portal URL ##
https://portal.azure.com/#view/Microsoft_Azure_Automation/UpdateCenterMenuBlade/

**Comment by adamfowlerit** [comment]
When I test this, it just takes me to the main https://portal.azure.com/#home page - does it need an automation account to be created first @OrionWithrow-OHIT ?

**Comment by OrionWithrow-OHIT** [comment]
Try this: https://portal.azure.com/#view/Microsoft_Azure_Automation/UpdateCenterMenuBlade/~/gettingstarted

**Comment by adamfowlerit** [comment]
Ah that works! I've added it now in the Azure Sub Portal section, let me know if there's others worth adding!
