### ISSUE TITLE
[MissingPortal] Azure Monitor

### ISSUE THREAD

**Issue by OrionWithrow-OHIT** [adamfowlerit/msportals.io#288]
## Portal Name ##
Azure Monitor

## Portal URL ##
https://portal.azure.com/#view/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/~/overview

**Comment by adamfowlerit** [comment]
Added to the Azure IT Admin Portals - Sub Portal Links section. I've also added https://portal.azure.com/#allservices but I would have thought this would contain links like the above, but it doesn't! Thanks @OrionWithrow-OHIT
