### ISSUE TITLE
[FeatureRequest] Developers Page?

### ISSUE THREAD

**Issue by PsychoData** [adamfowlerit/msportals.io#69]
Just had a couple issues created for more developer-oriented endpoints/portals. 

https://github.com/adamfowlerit/msportals.xyz/issues/66 Adaptive Cards
https://github.com/adamfowlerit/msportals.xyz/issues/67 Actionable Messages Developer Dashboard

These do seem useful and it would be nice to get them added, however I worry we're going to start accumulating Dev portals very quickly if we go down this route. 

So far we have these that strike me as developer/development-related 
![image](https://user-images.githubusercontent.com/3719116/102621011-f6258880-410c-11eb-9409-31d7c9ae96ed.png)
![image](https://user-images.githubusercontent.com/3719116/102621041-050c3b00-410d-11eb-8e31-bd2a37d77ee0.png)
![image](https://user-images.githubusercontent.com/3719116/102621102-1bb29200-410d-11eb-87b7-22d081d30fff.png)
![image](https://user-images.githubusercontent.com/3719116/102628137-41dd2f80-4117-11eb-9fe5-38c6f3f0cbcf.png)

but there are also several that are mixed-purpose like [Graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) - or the Adaptive cards portal above - I use it as an IT Admin.

The whole category or "Playground" sites is kind of deep in itself 
in a few minutes of Googling around I found these ones I believe are new 
- [Query Playground](https://www.documentdb.com/sql/demo) 
- [PowerBI Embedded Playground](https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html)
- [MessageCard Playground](https://messagecardplayground.azurewebsites.net/)
- [Adaptive Cards Designer](https://adaptivecards.io/designer/)

and there are probably several more I don't know of. It might be worth making a whole "developers" page/tab

**Comment by PsychoData** [comment]
Hey - just found another one! [Outlook Dev Center - OAuth Sandbox](https://oauthplay.azurewebsites.net/)

and this site that would also fit the Dev portal
JWT/MS Token Decoder - [jwt.ms](https://jwt.ms/)
[Microsoft Graph Toolkit](https://mgt.dev/)

**Comment by Danielx64** [comment]
While I listed this in my other feature request, there is also https://status.dev.azure.com/ (for status purpose)

**Comment by adamfowlerit** [comment]
I say we add the ones we have, and if it becomes too much, Dev Portals get their own page - then hopefully more Devs submit more portals :)

**Comment by PsychoData** [comment]
and Playgrounds! 
I LOVE the playgrounds for testing out cards and such

**Comment by adamfowlerit** [comment]
OK I think we might juuust have enough room for a Developer button :)

**Comment by PsychoData** [comment]
Overall, I kind of think we're getting to a level where there are several overlapping cross-sections

For Example, Visual Studio portals and Designer tools don't show up when you search "Dev" but show under the Developer Portals section.  And then Azure DevOps Status, Azure Lighthouse, and Customer Digital Experiences 
are under "Other" portals right now - but could definitely be useful for non-devs. Same for a lot of the sandbox/playground/designer tools 

"Developer Portals" section on the default page - [this](https://msportals.io/?search=#developer-portals)
![image](https://user-images.githubusercontent.com/3719116/104140054-6d9daf00-537d-11eb-8e04-cedf039823d1.png)

But if you Search for "dev" on the same page - [this](https://msportals.io/?search=dev)
![image](https://user-images.githubusercontent.com/3719116/104140073-86a66000-537d-11eb-9e50-3281fc6711ed.png)

**Comment by adamfowlerit** [comment]
I get your point, a lot of these admin portals are hard to categorise in a single area, and what about DevOps :P . I guess the favorites option helps people pick the ones they want to see for a condensed view. Doubling up entries across different pages to address it seems like a bad idea, which now I think of all that, was probably why I left the developer stuff under the standard admin portals section :)

**Comment by PsychoData** [comment]
This would likely get fixed as part of #91

**Comment by PsychoData** [comment]
The developer stuff - updated 
Some of these fit Admin or User and ALSO Dev, but I think at least all of these would make sense on a Dev page/category if we made one

![image](https://user-images.githubusercontent.com/3719116/145612854-11c22ff9-bd22-485e-a96e-7e782ce491f1.png)
![image](https://user-images.githubusercontent.com/3719116/145607961-bd94b5f6-aebb-4c41-8488-d319c005dc23.png)
![image](https://user-images.githubusercontent.com/3719116/145608050-d8a29d3e-0ff7-46c5-ad8f-7ebcacac0cfd.png)
![image](https://user-images.githubusercontent.com/3719116/145612396-9b07e280-8bdc-4450-83a0-6a3f7d7e7d3f.png)

**Comment by adamfowlerit** [comment]
Nice work - I think we just have to put them where they best fit, and I'd hope most people just use the filter anyway so the sections arent overly useful, just makes it a bit cleaner overall

**Comment by PsychoData** [comment]
Yeah, part of it for me is that I don't think a lot of Devs would have
access to many admin portals.

For example Power platform - they would have maybe the end user portal, a
solution, and maybe independent software vendors - but I think most would
not have the Power Platform Admin portal  to manage all of the solutions
across the whole environment

I think one day have the "one page" approach and a "dev" tag might be
useful - but that would take some rewriting

**Comment by adamfowlerit** [comment]
I suspect trying to define what a developer uses and doesn't use is going to have too much grey area, so I'm going to close this one
