### ISSUE TITLE
[FeatureRequest] Add link to status pages

### ISSUE THREAD

**Issue by Danielx64** [adamfowlerit/msportals.io#71]
**Is your feature request related to a problem? Please describe.**
Just like there are many admins portals,s there are also many places to get status info, for many different Microsoft services

**Describe the solution you'd like**
Just like having lists for different Microsoft portals, have a list of the different Microsoft status pages.

**Additional context**
Here's a list of status pages to get started:

https://status.office.com/
https://portal.office.com/servicestatus
https://status.azure.com/status/
https://portal.azure.com/?source=akams%2F#blade/Microsoft_Azure_Health/AzureHealthBrowseBlade/serviceIssues (aka.ms link: https://aka.ms/azureservicehealth)
https://status.azure.com/en-us/status?service=active-directory
https://status.dev.azure.com/

https://twitter.com/MSFT365Status
https://twitter.com/AzureSupport

More to come when I get back on my work laptop.

**Comment by adamfowlerit** [comment]
I think this is a good idea and probably deserves it's own button. With the minimal US Govt type links, maybe we revert those to extra buttons like the aka.ms ones? @PsychoData feel free to weigh in.

**Comment by adamfowlerit** [comment]
In the meantime, I've created a section on the main page for Health / Status pages:

https://msportals.io/?search=#health-status-portals

Only 2 entries so far, will find some time to add them soon or someone else feel free to do it based on @Danielx64 's list :)

**Comment by Danielx64** [comment]
Where did you want to add then?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by adamfowlerit** [comment]
It'll be in here: https://github.com/adamfowlerit/msportals.io/blob/master/_data/portals/admin.json

**Comment by Danielx64** [comment]
Ok leave it with me, I'll buy some time to do it tonight

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
