### ISSUE TITLE
[BUG] Menu Links Aren't Working As Expected

### ISSUE THREAD

**Issue by adamfowlerit** [adamfowlerit/msportals.io#72]
A menu link such as:

https://msportals.xyz/userportals?search=#end-user-portals-microsoft-365-apps

which should jump you to the End User Portals - Microsoft 365 Apps section, seems to jump there for a moment, then go to the top of the page if you access it via that URL.

If you are already on the site and click the menu link, it does jump down to that section being the top of the screen.

**Comment by PsychoData** [comment]
Made a fix for this 

A couple example URLs to test with

The original problem URL of https://msportals.xyz/userportals?search=#end-user-portals-microsoft-365-apps demo'd on my test site with the fix https://msportals.contoso.one/userportals?search=#end-user-portals-microsoft-365-apps

Filters and then scrolls to the correct place
http://msportals.contoso.one/?search=azure#azure-it-admin-portals-sub-portal-links

Filters, scrolls, and then has some sections yanked out from under it, and but Developer Portals is still showing as close as possible to the top of the screen
http://msportals.contoso.one/?search=azure#developer-portals

Same thing, but with security that has  juuuust enough room to scroll back onscreen in my laptop
http://msportals.contoso.one/?search=azure#security-defender-it-admin-portals

NOTE that if you load a page with an anchor, scroll, and then try to reload through F5 it will attempt to scroll you back to the correct header on the page you had listed before, but in certain cases the browser tries to preserve your position you were scrolled to and doesn't scroll back to the right place, even though I tried to tell it to

**Comment by PsychoData** [comment]
@adamfowlerit  if those links in my previous comment look like they are working right for you - Linked PR https://github.com/adamfowlerit/msportals.io/pull/81 should be good to go
