### ISSUE TITLE
[MissingPortal] MyStaff

### ISSUE THREAD

**Issue by pminnebach** [adamfowlerit/msportals.io#88]
## Portal Name ##

MyStaff

## Portal URL ##

https://mystaff.microsoft.com/

## What portal page and section would this fit best on? ##

Home page, not sure which subcategory would fit the most.

**Comment by PsychoData** [comment]
Part of me wants to say "end user" since it isn't an administrator portal.


Another part says this is for managers to administrate their staff...?

**Comment by PsychoData** [comment]
User side of [MyStaff](https://docs.microsoft.com/en-us/azure/active-directory/user-help/my-staff-team-manager)

So - eh - it's delegating Administrative rights to reset/manage their staff's

**Comment by adamfowlerit** [comment]
Hmm I'd be leaning on being an admin portal then, even though I agree it's not as clear cut as the others.

**Comment by adamfowlerit** [comment]
I've now added the portal and a aka.ms link for it, thanks!
