### ISSUE TITLE
[MissingPortal] Bing Maps

### ISSUE THREAD

**Issue by howff** [adamfowlerit/msportals.io#92]
## Portal Name ##

Bing Maps

## Portal URL ##

Microsoft think that they have this as their main portal, and it does look good
https://docs.microsoft.com/en-us/bingmaps/

but they don't link to the thing which they actually call the Bing Maps Portal, which looks worse, but in fact has the stuff you need
https://www.bingmapsportal.com/

Sorry, I don't understand your categories to know where this fits best

**Comment by adamfowlerit** [comment]
Thanks for the submission, will add soon!
