### ISSUE TITLE
[FeatureRequest] Light theme

### ISSUE THREAD

**Issue by SanderSade** [adamfowlerit/msportals.io#94]
Light theme for the website, please.

While dark themes are all the rage, they are unusable for most people with astigmatism ([1](https://www.androidauthority.com/dark-mode-1046425/), [2](https://www.vice.com/en/article/ywyqxw/apple-dark-mode-eye-strain-battery-life), [3](https://levelup.gitconnected.com/why-dark-mode-causes-more-accessibility-issues-than-it-solves-d2f8359bb46a)), causing eye strain and headaches. Somewhere 30..50% of the population has astigmatism.

**Comment by tjames192** [comment]
> Light theme for the website, please.
> 
> While dark themes are all the rage, they are unusable for most people with astigmatism ([1](https://www.androidauthority.com/dark-mode-1046425/), [2](https://www.vice.com/en/article/ywyqxw/apple-dark-mode-eye-strain-battery-life), [3](https://levelup.gitconnected.com/why-dark-mode-causes-more-accessibility-issues-than-it-solves-d2f8359bb46a)), causing eye strain and headaches. Somewhere 30..50% of the population has astigmatism.

Hi SanderSade, I have created an Edge extension that may help with your issue.
[msportals.io Edge Extension](https://github.com/tjames192/MicrosoftEdge-Extention-msportals.io)

**Comment by SmithPlatts** [comment]
While the extension looks really neat @tjames192, it'd be great for mobile, and situations where you can't use/install extensions, for the site to support a light theme.

**Comment by tjames192** [comment]
That is a good idea .. I hadn’t thought about that when implementing the extension. I’m not apposed to adding code to make the extension mobile friendly maybe that would be better suited for the main site or as a page.
Not sure what our options are .. maybe @adamfowlerit can comment.

**Comment by adamfowlerit** [comment]
Would love to have this option for accessibility reasons, go for it!

**Comment by jlaundry** [comment]
Looking at the [source jekyll theme](https://github.com/pages-themes/hacker), there doesn't appear to be a Light variant... so instead I've had a go at creating one.

Live demo: https://jlaundry.github.io/msportals.io/

Instead of creating an explicit light/dark mode button, the way I've done this respects the user's browser setting, so if you're still seeing the Dark theme, you'll need to change your OS/Browser setting.

**Comment by SanderSade** [comment]
> Thoughts/feedback please!

Works very well for me. Thank you!

**Comment by adamfowlerit** [comment]
Works great, but I'd also love to see a user controllable toggle - use the system default as the default msportals.io exp though!
