### ISSUE TITLE
[MissingPortal] M365 Admin Center

### ISSUE THREAD

**Issue by bandwannabe** [adamfowlerit/msportals.io#95]
## Portal Name ##

Microsoft 365 Admin Center

## Portal URL ##

What is the main URL/Site we are missing
https://portal.microsoft.com

## Secondary Portal URLs ##

We try to add aka.ms links wherever we can. Do you know of a related aka.ms link for your suggestion?
Example: <https://aka.ms/teamsadmincenter>

## What portal page and section would this fit best on? ##

We are currently making our web-pages from JSON files, which page and section does this fit best with?

## Special Notes ##

On some of the portals, we have been adding notes. For example

Example: Using the notes to make old product name searchable for Defender products.
![Defender for Endpoint is shown with "previously Defender ATP"](https://i.imgur.com/t8by69w.png)

Example: The new versus old Exchange Portals shown below.  
![Website has two Exchange Admin Centers with the New and Old portals noted](https://i.imgur.com/mjX0gS7.png)

## Additional context ##

Suggestions or context for the portals that we should have?

**Comment by PsychoData** [comment]
This is just an alias of admin.microsoft.com, too many to add them all I think, but we might be able to hide it in the HTML so that it will still match if you search for it. 

```
DNS Name=portal.microsoft.com
DNS Name=admin.microsoft.com
DNS Name=admin.microsoft365.com
DNS Name=portal.office365.com
```

For what it's worth, I had only used `portal.office365.com` and then `admin.microsoft.com` before. I think the others are just typo-catching domains.

**Comment by PsychoData** [comment]
Hmm I updated it with a couple Secondary URLs to add the Old Link (https://portal.office365.com) and an "Alt" (https://portal.microsoft.com) link. 

![image](https://user-images.githubusercontent.com/3719116/106922726-541d2800-66db-11eb-88ed-f9deb351a08e.png)

Not sure I'm thrilled with how they look if you need that many though.... and technically `admin.microsoft365.com` still wouldn't match.... 
We might need just a place that is rendered in the HTML as a comment (which would still make it searchable, without it showing visually) but that is something to solve in another issue
