### ISSUE TITLE
[FeatureRequest] Add column for required role assignments

### ISSUE THREAD

**Issue by Troy-Phillips** [adamfowlerit/msportals.io#99]
## Is your feature request related to a problem? Please describe ##
Not related to a problem

## Describe the solution you'd like ##

For most of the Admin centers a designated role assignment is required to Read or Edit content within them.  It would be nice if that associated information was in the list

## Describe alternatives you've considered ##

It's a really great list today, this is just an enhancement

## Additional context ##

The reader roles are not as important as the edit roles.   Thank you!

**Comment by PsychoData** [comment]
Some of this may also depend on your tenants configuration. 

For example, https://aad.portal.azure.com/ may not work if you are just a User, but will work with most of the Admin Roles. But it DOES usually work as a user by default. Rather variable situation. 

or [Conditional Access](https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ConditionalAccessBlade/Policies) does not work as a User, but does work as various types of Administrator, and at various levels of functionality. 

I kind of think this would be too specific and extensive, and the most that might make sense is some kind of "Permissions required" icon? 
But, I mean that's nearly all of the Admin links 

..maybe a "Login Required" link, but ... that's going to be basically everything internal or admin that isn't most of the Status pages.

**Comment by adamfowlerit** [comment]
It's a tough one - do we just link to the main docs.microsoft.com page for each product to cover questions about it, including permissions?

**Comment by adamfowlerit** [comment]
I had a concept of having a link to the top level documentation against every single portal link, but it quickly becomes complicated when you then think about adding a link to the permission required. I feel like this should actually be a completely separate solution someone builds purely around permissions :)
